informatika/urls.py
from django.conf.urls import include,url
from django.contrib import admin
import landing.urls
import dashboard.urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^fkiadmin000/', admin.site.urls),
    url(r'^', include('landing.urls',namespace='home')),
    url(r'^', include('dashboard.urls',namespace='dashboard')),
    url(r'^captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^berita/berita/$', views.berita, name='berita'),
    url(r'^berita/pengumuman/$', views.pengumuman, name='pengumuman'),
    url(r'^berita/pengumuman/(?P<slug>[\w-]+)/$', views.detail_pengumuman, name='detail_pengumuman'),
    url(r'^berita/detail/(?P<slug>[\w-]+)/$', views.detail_berita, name='detail_berita'),
    url(r'^berita/galeri/$', views.galeri, name='galeri'),
    url(r'^profil/informatika/$', views.identitas, name='profil'),
    url(r'^profil/identitas/$', views.identitas, name='identitas'),
    url(r'^profil/staff/$', views.staff, name='staff'),
    url(r'^profil/visi/$', views.visi, name='visi'),
    url(r'^profil/prestasi/$', views.prestasi, name='prestasi'),
    url(r'^kurikulum/$', views.kurikulum, name='kurikulum'),
    url(r'^ukm/fosti/$', views.fosti, name='fosti'),
    url(r'^ukm/himatif/$', views.himatif, name='himatif'),
    url(r'^alumni/$', views.alumni, name='alumni'),
    url(r'^akademik/dokumen/$', views.dokumen, name='dokumen'),



    # url(r'^berita/$', views.listBerita, name='berita'),
    # url(r'^adm/detail_berita/(?P<id>\d+)/$', views.detail_berita, name='detail_berita'),
    # url(r'^timeline/$', views.view_timeline, name='timeline'),




]

templates/profil/identitas.html
{% extends 'base.html' %}
{% load staticfiles   %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/custom-pages.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/ghost-btn.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

{% endblock css %}


{% block content %}
<div class="container-fluid animated fadeIn" id="page-container">
<br />
  <div class="col-md-10 col-md-offset-1">

  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Beranda</a></li>
    <li class="breadcrumb-item"><a href="{% url 'home:profil' %}">Profil</a></li>
   <li class="breadcrumb-item active">Identitas</li>
  </ol>

<div class="page-header animated fadeIn"><h1 id="page-header"> <i class="fa fa-institution" aria-hidden="true"></i> {{judul}} <small>Serba-serbi Prodi Informatika</small></h1> </div>
  </div>
  <div class="col-md-10 col-md-offset-1">


  <h4>Program Studi&nbsp;&nbsp;&nbsp;:&nbsp;Informatika (Informatics)</h4>
  <h4>Jenjang&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;S1 (Sarjana)</h4>
  <h4>Tanggal Berdiri&nbsp; : 20 April 2007</h4>
  <h4>No. SK Pendirian : Surat Keputusan (SK) Ijin Dirjen Dikti No. 930/D/T2007 Tanggal 20 April 2007</h4>
  <br /><br />
  <p>

  <div class="col-md-5">
    <img src="{% static 'img/lab/IMG_3112.jpg' %}" alt="..." class="img-thumbnail img-responsive pull-left">
  </div>
    <p class='text-justify lead' id="para-konten">Sejarah berdirinya Program Studi Informatika Universitas Muhammadiyah Surakarta (UMS) diawali dengan pemikiran perlunya mengembangkan konsentrasi Sistem Komputer dan Informatika Jurusan Teknik Elektro UMS dan meningkatkan statusnya menjadi program studi sendiri untuk mencukupi kebutuhan tenaga kerja di bidang teknologi informasi.   Secara formal, Program Studi Informatika UMS adalah Program Studi yang berdiri pada tahun 2007 melalui surat keputusan <b>(SK) Ijin Dirjen Dikti No. 930/D/T2007 Tanggal 20 April</b> dengan konsentrasi pada Perangkat Lunak (Software), meliputi: </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;1.&nbsp; Sistem Informasi</b></li>
        <li><b>&nbsp;2.&nbsp; Sistem Jaringan Komputer</b></li>
        <li><b>&nbsp;3.&nbsp; Rekayasa</b></li>
      </ol>
      <br />
    <br />
    <p class="text-justify" id="para-konten">Pada tanggal 29 Desember 2011, Program Studi Informatika mendapatkan akreditasi B (Baik) dari Badan Akreditasi Nasional Perguruan Tinggi melalui Surat Keputusan (SK) Nomor 047/BAN-PT/Ak-XIV/S1/XII/2011 tertanggal 29 Desember 2011.</p>
    <p class="text-justify" id="para-konten">Untuk menyesuaikan dengan perkembangan teknologi dan kebutuhan dunia kerja, maka konsentrasi yang ada di program studi Informatika mengalami perluasan cakupan menjadi:</p>

    <ol class="list-unstyled" id="para-konten">
      <li><b>&nbsp;1.&nbsp; Sistem Informasi dan Entreprise (SIE)</b></li>
      <li><b>&nbsp;2.&nbsp; Sistem Jaringan dan Multimedia (SJM)</b></li>
      <li><b>&nbsp;3.&nbsp; Rakayasa Perangkat Lunak dan animasi (RPLA)</b></li>
    </ol>
    <br />

    <div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="https://www.youtube.com/embed/morqjXvEnU8"></iframe>
    </div>
    <hr />
    <p class='text-justify lead' id="para-konten">Dalam tata kelola universitas, Program Studi Informatika Universitas Muhammadiyah Surakarta (UMS) termasuk kedalam Fakultas Komunikasi dan Informatika (FKI). Semua pelayanan administrasi dan kegiatan belajar mengajar (semua kegiatan perkuliahan dan praktikum) dilaksanakan di Gedung J kompleks kampus II UMS yang terletak di Jl. A. Yani, Pabelan, Kartasura Sukoharjo. Informatika UMS berusaha selalu menjaga dan meningkatkan fasilitas pembelajaran baik ruang kuliah maupun laboratorium agar selalu sesuai dengan perkembangan zaman. Laboratorium yang saat ini ada di Program Studi Informatika UMS adalah:</p>
    <ol class="list-unstyled" id="para-konten">
      <li><b>&nbsp;1.&nbsp; Laboratorium Komputer Fakultas </b>(digunakan bersama-sama dengan program studi Ilmu Komunikasi)</li>
      <li><b>&nbsp;2.&nbsp; Laboratorium Sistem Informasi</b></li>
      <li><b>&nbsp;3.&nbsp; Laboratorium Komputer Jaringan</b></li>
      <li><b>&nbsp;4.&nbsp; Laboratorium Perangkat Lunak</b></li>
    </ol>

    <br />
    <br />
    <ul class="thumbnails list-unstyled">
            <div class="row">
            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3146.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Komputer Fakultas</h2>
                  <!-- <p>(Digunakan bersama dengan prodi komunikasi)</p> -->
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>

            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3143.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Sistem Informasi</h2>
                  <!-- <p>My project description</p> -->
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>
  <!-- row -->
            </div> <!-- row -->
            <div class="row">

            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3112.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Komputer Jaringan</h2>
                  <!-- <p>My project description</p> -->
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>

            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3146.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Perangkat Lunak</h2>
                  <!-- <p>My project description</p> -->
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>
          </div><!-- row -->
      </ul>


    <br />
    <p class="text-justify" id="para-konten">Fasilitas laboratorium tersebut diatas digunakan untuk kegiatan praktikum dan penelitian baik oleh dosen maupun oleh mahasiswa (tugas akhir/skripsi). Untuk memenuhi kebutuhan pustaka, kegiatan belajar mengajar didukung penuh oleh perpustakaan pusat UMS yang menyediakan buku-buku yang lengkap. Disamping itu, program studi menyediakan koleksi buku-buku, jurnal, majalah, prosiding dan lain-lain yang belum ada di perpustakaan yang dapat dipinjam baik oleh dosen maupun mahasiswa.</p>
    <p class="text-justify" id="para-konten">Jumlah mahasiswa per angkatan rata-rata adalah 160-200 mahasiswa. Total mahasiswa aktif pada semester genap tahun ajaran 2014/2015 adalah 651 mahasiswa.</p>
    <p class="text-justify" id="para-konten">Staff pengajar Program Studi Informatika mempunyai basis pengetahuan yang menunjang arah pengembangan keilmuan dalam bidang Informatika dengan berbagai strata lulusan, terdiri dari 1 orang Profesor (Guru Besar), 7 orang Doktor (S3), 13 orang Master (S2), dan beberapa tenaga pengajar yang masih Sarjana (S1).</p>


    <br />
    <a href="{% url 'home:staff' %}"><button class="btn btn-ghost-black btn-lg" role="button" id="btnTestimoni">LIHAT STAFF PENGAJAR</button></a>
</div>

</div> <!-- container-fluid -->
{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/profil/prestasi.html
{% extends 'base.html' %}
{% load staticfiles   %}

{% block css %}
<link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/custom-pages.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

{% endblock css %}


{% block content %}
<div class="container-fluid animated fadeIn" id="page-container">
<br />
  <div class="col-md-10 col-md-offset-1">

  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Beranda</a></li>
    <li class="breadcrumb-item"><a href="{% url 'home:profil' %}">Profil</a></li>
   <li class="breadcrumb-item active">Prestasi</li>
  </ol>

<div class="page-header animated fadeIn"><h1 id="page-header">{{judul}} <small>Prestasi Prodi Informatika</small></h1> </div>
  </div>
  <div class="col-md-10 col-md-offset-1">

</div>

</div> <!-- container-fluid -->
{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/profil/profil.html
{% extends 'base.html' %}
{% load staticfiles   %}

{% block css %}
<link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/custom-pages.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

{% endblock css %}


{% block content %}

<!-- Tempat untuk konten profil -->

<div class="container-fluid animated fadeIn" id="page-container">
<br />
  <div class="col-md-10 col-md-offset-1">

  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Beranda</a></li>
    <li class="breadcrumb-item"><a href="{% url 'home:profil' %}">Profil</a></li>
   <li class="breadcrumb-item active">Profil Prodi</li>
  </ol>

<div class="page-header animated fadeIn"><h1 id="page-header">{{judul}} <small>Profil Prodi Informatika</small></h1> </div>
  </div>
  <div class="col-md-10 col-md-offset-1">

  <br /><br />
  <p>
  <div class="row">
  <div class="col-md-12">

    <div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="https://www.youtube.com/embed/morqjXvEnU8"></iframe>
    </div>
    <hr />
    <p class='text-justify lead' id="para-konten">Dalam tata kelola universitas, Program Studi Informatika Universitas Muhammadiyah Surakarta (UMS) termasuk kedalam Fakultas Komunikasi dan Informatika (FKI). Semua pelayanan administrasi dan kegiatan belajar mengajar (semua kegiatan perkuliahan dan praktikum) dilaksanakan di Gedung J kompleks kampus II UMS yang terletak di Jl. A. Yani, Pabelan, Kartasura Sukoharjo. Informatika UMS berusaha selalu menjaga dan meningkatkan fasilitas pembelajaran baik ruang kuliah maupun laboratorium agar selalu sesuai dengan perkembangan zaman. Laboratorium yang saat ini ada di Program Studi Informatika UMS adalah:</p>
    <ol class="list-unstyled" id="para-konten">
      <li><b>&nbsp;1.&nbsp; Laboratorium Komputer Fakultas </b>(digunakan bersama-sama dengan program studi Ilmu Komunikasi)</li>
      <li><b>&nbsp;2.&nbsp; Laboratorium Sistem Informasi</b></li>
      <li><b>&nbsp;3.&nbsp; Laboratorium Komputer Jaringan</b></li>
      <li><b>&nbsp;4.&nbsp; Laboratorium Perangkat Lunak</b></li>
    </ol>
    </div>
    </div>
    <br />
    <br />
    <ul class="thumbnails list-unstyled">
            <div class="row">
            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3146.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Komputer Fakultas</h2>
                  <p>(Digunakan bersama dengan prodi komunikasi)</p>
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>

            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3143.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Sistem Informasi</h2>
                  <p>My project description</p>
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>
  <!-- row -->
            </div> <!-- row -->
            <div class="row">

            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3112.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Komputer Jaringan</h2>
                  <p>My project description</p>
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>

            <li class="col-md-6">
              <div class="thumbnail" style="padding: 0">
                <div style="padding:4px">
                  <img alt="300x200" style="width: 100%" src="{% static 'img/lab/IMG_3146.jpg' %}">
                </div>
                <div class="caption">
                  <h2>Laboratorium Perangkat Lunak</h2>
                  <p>My project description</p>
                  <p><i class="fa fa-map-pin"></i> Ruang 1, Lantai 3</p>
                </div>
              </div>
            </li>
          </div><!-- row -->
      </ul>


    <br />
    <p class="text-justify" id="para-konten">Fasilitas laboratorium tersebut diatas digunakan untuk kegiatan praktikum dan penelitian baik oleh dosen maupun oleh mahasiswa (tugas akhir/skripsi). Untuk memenuhi kebutuhan pustaka, kegiatan belajar mengajar didukung penuh oleh perpustakaan pusat UMS yang menyediakan buku-buku yang lengkap. Disamping itu, program studi menyediakan koleksi buku-buku, jurnal, majalah, prosiding dan lain-lain yang belum ada di perpustakaan yang dapat dipinjam baik oleh dosen maupun mahasiswa.</p>
    <p class="text-justify" id="para-konten">Jumlah mahasiswa per angkatan rata-rata adalah 160-200 mahasiswa. Total mahasiswa aktif pada semester genap tahun ajaran 2014/2015 adalah 651 mahasiswa.</p>
    <p class="text-justify" id="para-konten">Staff pengajar Program Studi Informatika mempunyai basis pengetahuan yang menunjang arah pengembangan keilmuan dalam bidang Informatika dengan berbagai strata lulusan, terdiri dari 1 orang Profesor (Guru Besar), 7 orang Doktor (S3), 13 orang Master (S2), dan beberapa tenaga pengajar yang masih Sarjana (S1).</p>


    <br />

      <div class="col-md-4">

      </div>
      <div class="col-md-4">

      </div>
      <div class="col-md-4">


      </div>

</div>

</div> <!-- container-fluid -->

{% endblock content %}


{% block scripts %}
{% endblock scripts %}

templates/profil/visi.html
{% extends 'base.html' %}
{% load staticfiles   %}

{% block css %}
<link href="https://fonts.googleapis.com/css?family=PT+Serif" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/custom-pages.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/visi.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

{% endblock css %}


{% block content %}
<div class="container-fluid animated fadeIn" id="page-container">
<br />
  <div class="col-md-10 col-md-offset-1">

  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Beranda</a></li>
    <li class="breadcrumb-item"><a href="{% url 'home:profil' %}">Profil</a></li>
   <li class="breadcrumb-item active">Visi dan Misi</li>
  </ol>

    <div class="page-header animated fadeIn"><h1 id="page-header"><i class="fa fa-institution" aria-hidden="true"></i> {{judul}} <small>{{subJudul}}</small></h1> </div>
  </div>
  <div class="col-md-10 col-md-offset-1">

    <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
              <div class="box">
                  <div class="box-icon">
                      <span class="fa fa-4x fa-eye"></span>
                  </div>
                  <div class="info">
                      <br />
                      <h4 class="text-center">VISI</h4>
                      <p>Pada Tahun 2035, Program Studi Informatika menjadi Pusat Unggulan dalam penerapan dan pengembangan iptek di bidang informatika serta pengembangan sumber daya manusia berdasarkan nilai-nilai keislaman.</p>
                      <!-- <a href="" class="btn">Link</a> -->
                  </div>
              </div>
          </div>

          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
              <div class="box">
                  <div class="box-icon">
                      <span class="fa fa-4x fa-rocket"></span>
                  </div>
                  <div class="info">
                      <br />
                      <h4 class="text-center">MISI</h4>
                      <p>1. Mendidik mahasiswa agar menguasai iptek di bidang informatika berdasarkan nilai-nilai keislaman, sesuai kompetensi akademik dan professional</p>
                      <p>2. Mengembangkan ilmu melalui kegiatan penelitian dalam bidang informatika, baik teoritis maupun terapan</p>
                      <p>3. Menyebarluaskan ilmu pengetahuan dan teknologi informatika melalui kemitraan dan pengabdian kepada masyarakat dalam rangka membentuk masyarakat berwawasan teknologi</p>
                      <!-- <a href="" class="btn">Link</a> -->
                  </div>
              </div>
          </div>
          </br>
          </br>
          </br>
    <div class="col-md-12">
    </br>
    </br>
    </br>
      <h2>Penjabaran Pokok-pokok Pikiran Tentang Visi dan Misi</h2>
      <hr />
      <p class='text-justify lead' id="para-konten">Pokok-pokok pikiran tentang visi dan misi dapat dijabarkan sebagai berikut:<br />
      1. Pengertian sebagai pusat unggulan adalah bahwa ada produk yang dihasilkan oleh Program Studi Informatika Universitas Muhammadiyah Surakarta diakui, dibutuhkan dan dijadikan sebagai pilihan oleh masyarakat, baik tingkat lokal, nasional, regional, maupun internasional di bidang:
      </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;a.&nbsp; Rekayasa Perangkat Lunak </b></li>
        <li><b>&nbsp;b.&nbsp; Game dan animasi</b></li>
        <li><b>&nbsp;c.&nbsp; Sistem Informasi</b></li>
        <li><b>&nbsp;d.&nbsp; Sistem Jaringan Komputer</b></li>
        <li><b>&nbsp;e.&nbsp; Sistem Perangkat Mobile</b></li>
        <li><b>&nbsp;f.&nbsp; Aplikasi berbasis web</b></li>
      </ol>
      <p class='text-justify lead' id="para-konten">2. Penerapan didahulukan terlebih dahulu kemudian baru pengembangan. Maksudnya menerapkan iptek yang sudah ada, kemudian dikembangkan sesuai dengan kemampuan.<br />
      3. Sumber daya manusia meliputi dosen, karyawan, dan mahasiswa. <br />
      4. Berdasarkan nilai-nilai keislaman maksudnya dalam menerapkan iptek di bidang informatika harus didasarkan pada ajaran islam. <br />
      5. Pengertian profesional adalah sesuai dengan etika profesi.<br />
      6. Berwawasan teknologi adalah tidak gagap teknologi.<br />

      </p>
      <br />
      <br />
      <h2>Tujuan Program Studi</h2>
      <hr />
      <p class='text-justify lead' id="para-konten">1. Menghasilkan lulusan sarjana informatika yang mampu mengadopsi, menerapkan dan mengembangkan iptek di bidang informatika dengan kompetensi sebagai berikut :
      </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;a.&nbsp; Mampu Menerapkan Ilmunya Secara Professional </b></li>
        <li><b>&nbsp;b.&nbsp; Mampu beradaptasi dan memberi arah perkembangan teknologi</b></li>
        <li><b>&nbsp;c.&nbsp; Mempunyai kesadaran akan nilai-nilai keislaman</b></li>
      </ol>
      <p class='text-justify lead' id="para-konten">2. Menghasilkan produk ilmu pengetahuan di bidang :
      </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;a.&nbsp; Rekayasa Perangkat Lunak </b></li>
        <li><b>&nbsp;b.&nbsp; Game dan animasi</b></li>
        <li><b>&nbsp;c.&nbsp; Sistem Informasi</b></li>
        <li><b>&nbsp;d.&nbsp; Sistem Jaringan Komputer</b></li>
        <li><b>&nbsp;e.&nbsp; Sistem Perangkat Mobile</b></li>
        <li><b>&nbsp;f.&nbsp; Aplikasi berbasis web</b></li>
      </ol>
      <br />
      <br />
      <h2>Strategi</h2>
      <hr />
      <p class='text-justify lead' id="para-konten">1. Untuk menghasilkan lulusan sarjana informatika yang mampu mengadopsi, menerapkan dan mengembangkan iptek di bidang informatika yang mampu menerapkan ilmunya secara professional, ditetapkan strategi:
      </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;a.&nbsp; Meningkatkan mutu pembelajaran</b></li>
        <li><b>&nbsp;b.&nbsp; Meningkatkan kualifikasi staf akademik</b></li>
        <li><b>&nbsp;c.&nbsp; Meningkatkan soft skill mahasiswa</b></li>
      </ol>
      <p class='text-justify lead' id="para-konten">2. Untuk menghasilkan lulusan sarjana informatika yang mampu beradaptasi dan memberi arah perkembangan teknologi, ditetapkan strategi:
      </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;a.&nbsp; Meningkatkan keterlibatan mahasiswa dalam penelitian</b></li>
        <li><b>&nbsp;b.&nbsp; Membimbing aktif mahasiswa dalam mengikuti kompetisi karya ilmiah</b></li>
      </ol>
      <p class='text-justify lead' id="para-konten">3. Untuk menghasilkan lulusan sarjana informatika yang mempunyai kesadaran akan nilai-nilai keislaman ditetapkan strategi:
      </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;a.&nbsp; Membekali mahasiswa dengan nilai-nilai keislaman melalui mata kuliah wajib</b></li>
        <li><b>&nbsp;b.&nbsp; Mendukung program kajian keislaman yang diselenggarakan oleh Universitas</b></li>
      </ol>
      <p class='text-justify lead' id="para-konten">4. Untuk menghasilkan produk ilmu pengetahuan di bidang rekayasa perangkat lunak, game dan animasi, sistem informasi, sistem jaringan komputer, sistem perangkat mobile, dan aplikasi berbasis web maka ditetapkan strategi:
      </p>
      <ol class="list-unstyled" id="para-konten">
        <li><b>&nbsp;a.&nbsp; Meningkatkan penelitian dan publikasi sesuai bidang tersebut</b></li>
        <li><b>&nbsp;b.&nbsp; Memetakan studi lanjut dosen sesuai bidang tersebut</b></li>
      </ol>
      <hr />
    </div>
  	</div>

</div>

</div> <!-- container-fluid -->
{% endblock content %}


{% block scripts %}
{% endblock scripts %}