dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^dashboard/rekapan/$',views.cetak_rekapan_alumni, name='cetak_alumni'),
url(r'^dashboard/data_alumni/$',views.alumni_dashboard, name='alumni_dashboard'),
url(r'^dashboard/staff/$',views.staff, name='staff'),
url(r'^dashboard/dosen_tetap/$',views.dosen_tetap, name='dosen_tetap'),
url(r'^dashboard/dosen_profesi/$',views.dosen_profesi, name='dosen_profesi'),
url(r'^dashboard/tambah_staff/$',views.staff_tambah, name='tambah_staff'),
url(r'^dashboard/dosen_tetap/tambah_dosen_tetap/$',views.dosen_tetap_tambah, name='tambah_dosen_tetap'),
url(r'^dashboard/dosen_profesi/tambah_dosen_profesi/$',views.dosen_profesi_tambah, name='tambah_dosen_profesi'),
url(r'^dashboard/edit_staff/(?P<id>\d+)/$',views.staff_edit, name='edit_staff'),
url(r'^dashboard/dosen_tetap/edit_staff/(?P<id>\d+)/$',views.dosen_tetap_edit, name='edit_dosen_tetap'),
url(r'^dashboard/dosen_profesi/edit_staff/(?P<id>\d+)/$',views.dosen_profesi_edit, name='edit_dosen_profesi'),
url(r'^dashboard/hapus_staff/(?P<id>\d+)/$',views.staff_hapus, name='hapus_staff'),
url(r'^dashboard/hapus_dosen_tetap/(?P<id>\d+)/$',views.dosen_tetap_hapus, name='hapus_dosen_tetap'),
url(r'^dashboard/hapus_dosen_profesi/(?P<id>\d+)/$',views.dosen_profesi_hapus, name='hapus_dosen_profesi'),
url(r'^dashboard/gallery/$',views.gallery, name='gallery'),
url(r'^dashboard/gallery/tambah_gallery/$',views.gallery_tambah, name='tambah_gallery'),
url(r'^dashboard/gallery/edit_gallery/(?P<id>\d+)/$',views.gallery_edit, name='edit_gallery'),
url(r'^dashboard/gallery/hapus_gallery/(?P<id>\d+)/$',views.gallery_hapus, name='hapus_gallery'),
url(r'^dashboard/berita/tambah_berita/$',views.berita_tambah, name='tambah_berita'),
url(r'^dashboard/pengumuman/tambah_pengumuman/$',views.pengumuman_tambah, name='tambah_pengumuman'),
url(r'^dashboard/berita/edit_berita/(?P<slug>[\w-]+)/$',views.berita_edit, name='edit_berita'),
url(r'^dashboard/pengumuman/edit_pengumuman/(?P<slug>[\w-]+)/$',views.pengumuman_edit, name='edit_pengumuman'),
url(r'^dashboard/berita/hapus_berita/(?P<slug>[\w-]+)/$',views.berita_hapus, name='hapus_berita'),
url(r'^dashboard/pengumuman/hapus_berita/(?P<slug>[\w-]+)/$',views.pengumuman_hapus, name='hapus_pengumuman'),
url(r'^dashboard/berita/$',views.list_berita, name='berita'),
url(r'^dashboard/berita/(?P<slug>[\w-]+)/$',views.berita_detail,name='detail_berita'),
url(r'^dashboard/pengumuman/$',views.list_pengumuman, name='pengumuman'),
url(r'^dashboard/ukm/$',views.ukm, name='ukm'),
url(r'^dashboard/ukm/edit/(?P<id>\d+)/$',views.ukm_edit, name='edit_ukm'),
url(r'^dashboard/tambah_link/$',views.ukm_tambah, name='tambah_link'),
url(r'^dashboard/kurikulum/$',views.kurikulum, name='kurikulum'),
url(r'^dashboard/tambah_kurikulum/$',views.kurikulum_tambah, name='tambah_kurikulum'),
url(r'^dashboard/edit_kurikulum/(?P<id>\d+)/$',views.kurikulum_edit, name='edit_kurikulum'),
url(r'^dashboard/hapus_kurikulum/(?P<id>\d+)/$',views.kurikulum_hapus, name='hapus_kurikulum'),
url(r'^login/$', views.login_view, name='login'),
url(r'^logout/$', views.logout_view, name='logout'),
url(r'^dashboard/passwords/$', views.password_ubah, name='password'),
url(r'^dashboard/dokumen/$',views.dokumen, name='dokumen'),
url(r'^dashboard/dokumen/buat_dokumen/$',views.dokumen_tambah, name='tambah_dokumen'),
url(r'^dashboard/dokumen/hapus/(?P<id>\d+)/$',views.dokumen_hapus, name='hapus_dokumen'),
url(r'^dashboard/dokumen/edit/(?P<id>\d+)/$',views.dokumen_edit, name='edit_dokumen'),




]

informatika/urls.py
from django.conf.urls import include,url
from django.contrib import admin
import landing.urls
import dashboard.urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^fkiadmin000/', admin.site.urls),
    url(r'^', include('landing.urls',namespace='home')),
    url(r'^', include('dashboard.urls',namespace='dashboard')),
    url(r'^captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^berita/berita/$', views.berita, name='berita'),
    url(r'^berita/pengumuman/$', views.pengumuman, name='pengumuman'),
    url(r'^berita/pengumuman/(?P<slug>[\w-]+)/$', views.detail_pengumuman, name='detail_pengumuman'),
    url(r'^berita/detail/(?P<slug>[\w-]+)/$', views.detail_berita, name='detail_berita'),
    url(r'^berita/galeri/$', views.galeri, name='galeri'),
    url(r'^profil/informatika/$', views.identitas, name='profil'),
    url(r'^profil/identitas/$', views.identitas, name='identitas'),
    url(r'^profil/staff/$', views.staff, name='staff'),
    url(r'^profil/visi/$', views.visi, name='visi'),
    url(r'^profil/prestasi/$', views.prestasi, name='prestasi'),
    url(r'^kurikulum/$', views.kurikulum, name='kurikulum'),
    url(r'^ukm/fosti/$', views.fosti, name='fosti'),
    url(r'^ukm/himatif/$', views.himatif, name='himatif'),
    url(r'^alumni/$', views.alumni, name='alumni'),
    url(r'^akademik/dokumen/$', views.dokumen, name='dokumen'),



    # url(r'^berita/$', views.listBerita, name='berita'),
    # url(r'^adm/detail_berita/(?P<id>\d+)/$', views.detail_berita, name='detail_berita'),
    # url(r'^timeline/$', views.view_timeline, name='timeline'),




]

templates/dashboard/halaman/kurikulum/buat_kurikulum.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}
<div id="page-wrapper">
<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <ol class="breadcrumb">
                        <li>
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                            <li >
                                <i class=""></i> Halaman
                            </li>
                            <li class="active">
                                <i class=""></i> Kurikulum
                            </li>
                        </ol>
                        <h1 class="page-header">
                            Manajemen Kurikulum <small>Semua Manajemen Kurikulum</small>
                        </h1>
                    </div>
                    <div class="col-lg-12">
                    <div class="panel-body">
                        <form method="POST" action="" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form_kurikulum | crispy }}
                            <input type="submit" class="btn btn-primary" value="Simpan">
                            <!--<script>alert("Terima Kasih sudah mendaftar beasiswa, {{ user }}")</script>-->

                        </form>
                    </div>


                    </div>



                </div>


            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

    <!-- /#wrapper -->
{% endblock content %}

templates/dashboard/halaman/kurikulum/list_kurikulum.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}


{% block content %}
<div id="page-wrapper">
<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <ol class="breadcrumb">
                        <li>
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                            <li >
                                <i class=""></i> Halaman
                            </li>
                            <li >
                                <i class="active"></i> Kurikulum
                            </li>

                        </ol>
                        <h1 class="page-header">
                            Kurikulum <small>Kurikulum Prodi Informatika</small>
                        </h1>
                    </div>


                    <div class="col-lg-12">
                     <a href="{% url 'dashboard:tambah_kurikulum' %}" class="btn btn-primary"><i class="fa fa-plus"></i>Tambah Kurikulum</a><br/><br/>

                <div class="table-responsive">
                    <table class="table">
                        <tr class="info">
                            <td><strong>No</strong></td>
                            <td><strong>Semester</strong></td>
                            <td><strong>Nama Mata Kuliah</strong></td>
                            <td><strong>Kode MK</strong></td>
                            <td><strong>SKS</strong></td>
                            <td><strong>Status MK</strong></td>
                            <td><strong>Option</strong></td>


                        </tr>
                        {% for dt in kurikulum  %}
                        <tr class="default">
                            <td>{{forloop.counter}}</td>
                            <td>{{dt.semester}}</td>
                            <td>{{dt.makul}}</td>
                            <td>{{dt.kode}}</td>
                            <td>{{dt.sks}}</td>
                            {% if dt.wajib %}
                            <td><button class="btn-xs btn-success">MK. Wajib</button></td>
                            {% else %}
                            <td><button class="btn-xs btn-warning">MK. Pilihan</button></td>
                            {% endif %}
                            <td> <a href="{% url 'dashboard:edit_kurikulum' dt.id %}" class="btn btn-primary"><i class="fa fa-edit"></i></a> <a href="{% url 'dashboard:hapus_kurikulum' dt.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                            </td>

                        </tr>
                         {% endfor %}

                    </table>
                    </div>



                </div>


            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

    <!-- /#wrapper -->
{% endblock content %}