dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^dashboard/rekapan/$',views.cetak_rekapan_alumni, name='cetak_alumni'),
url(r'^dashboard/data_alumni/$',views.alumni_dashboard, name='alumni_dashboard'),
url(r'^dashboard/staff/$',views.staff, name='staff'),
url(r'^dashboard/dosen_tetap/$',views.dosen_tetap, name='dosen_tetap'),
url(r'^dashboard/dosen_profesi/$',views.dosen_profesi, name='dosen_profesi'),
url(r'^dashboard/tambah_staff/$',views.staff_tambah, name='tambah_staff'),
url(r'^dashboard/dosen_tetap/tambah_dosen_tetap/$',views.dosen_tetap_tambah, name='tambah_dosen_tetap'),
url(r'^dashboard/dosen_profesi/tambah_dosen_profesi/$',views.dosen_profesi_tambah, name='tambah_dosen_profesi'),
url(r'^dashboard/edit_staff/(?P<id>\d+)/$',views.staff_edit, name='edit_staff'),
url(r'^dashboard/dosen_tetap/edit_staff/(?P<id>\d+)/$',views.dosen_tetap_edit, name='edit_dosen_tetap'),
url(r'^dashboard/dosen_profesi/edit_staff/(?P<id>\d+)/$',views.dosen_profesi_edit, name='edit_dosen_profesi'),
url(r'^dashboard/hapus_staff/(?P<id>\d+)/$',views.staff_hapus, name='hapus_staff'),
url(r'^dashboard/hapus_dosen_tetap/(?P<id>\d+)/$',views.dosen_tetap_hapus, name='hapus_dosen_tetap'),
url(r'^dashboard/hapus_dosen_profesi/(?P<id>\d+)/$',views.dosen_profesi_hapus, name='hapus_dosen_profesi'),
url(r'^dashboard/gallery/$',views.gallery, name='gallery'),
url(r'^dashboard/gallery/tambah_gallery/$',views.gallery_tambah, name='tambah_gallery'),
url(r'^dashboard/gallery/edit_gallery/(?P<id>\d+)/$',views.gallery_edit, name='edit_gallery'),
url(r'^dashboard/gallery/hapus_gallery/(?P<id>\d+)/$',views.gallery_hapus, name='hapus_gallery'),
url(r'^dashboard/berita/tambah_berita/$',views.berita_tambah, name='tambah_berita'),
url(r'^dashboard/pengumuman/tambah_pengumuman/$',views.pengumuman_tambah, name='tambah_pengumuman'),
url(r'^dashboard/berita/edit_berita/(?P<slug>[\w-]+)/$',views.berita_edit, name='edit_berita'),
url(r'^dashboard/pengumuman/edit_pengumuman/(?P<slug>[\w-]+)/$',views.pengumuman_edit, name='edit_pengumuman'),
url(r'^dashboard/berita/hapus_berita/(?P<slug>[\w-]+)/$',views.berita_hapus, name='hapus_berita'),
url(r'^dashboard/pengumuman/hapus_berita/(?P<slug>[\w-]+)/$',views.pengumuman_hapus, name='hapus_pengumuman'),
url(r'^dashboard/berita/$',views.list_berita, name='berita'),
url(r'^dashboard/berita/(?P<slug>[\w-]+)/$',views.berita_detail,name='detail_berita'),
url(r'^dashboard/pengumuman/$',views.list_pengumuman, name='pengumuman'),
url(r'^dashboard/ukm/$',views.ukm, name='ukm'),
url(r'^dashboard/ukm/edit/(?P<id>\d+)/$',views.ukm_edit, name='edit_ukm'),
url(r'^dashboard/tambah_link/$',views.ukm_tambah, name='tambah_link'),
url(r'^dashboard/kurikulum/$',views.kurikulum, name='kurikulum'),
url(r'^dashboard/tambah_kurikulum/$',views.kurikulum_tambah, name='tambah_kurikulum'),
url(r'^dashboard/edit_kurikulum/(?P<id>\d+)/$',views.kurikulum_edit, name='edit_kurikulum'),
url(r'^dashboard/hapus_kurikulum/(?P<id>\d+)/$',views.kurikulum_hapus, name='hapus_kurikulum'),
url(r'^login/$', views.login_view, name='login'),
url(r'^logout/$', views.logout_view, name='logout'),
url(r'^dashboard/passwords/$', views.password_ubah, name='password'),
url(r'^dashboard/dokumen/$',views.dokumen, name='dokumen'),
url(r'^dashboard/dokumen/buat_dokumen/$',views.dokumen_tambah, name='tambah_dokumen'),
url(r'^dashboard/dokumen/hapus/(?P<id>\d+)/$',views.dokumen_hapus, name='hapus_dokumen'),
url(r'^dashboard/dokumen/edit/(?P<id>\d+)/$',views.dokumen_edit, name='edit_dokumen'),




]

informatika/urls.py
from django.conf.urls import include,url
from django.contrib import admin
import landing.urls
import dashboard.urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^fkiadmin000/', admin.site.urls),
    url(r'^', include('landing.urls',namespace='home')),
    url(r'^', include('dashboard.urls',namespace='dashboard')),
    url(r'^captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views



urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^berita/berita/$', views.berita, name='berita'),
    url(r'^berita/pengumuman/$', views.pengumuman, name='pengumuman'),
    url(r'^berita/pengumuman/(?P<slug>[\w-]+)/$', views.detail_pengumuman, name='detail_pengumuman'),
    url(r'^berita/detail/(?P<slug>[\w-]+)/$', views.detail_berita, name='detail_berita'),
    url(r'^berita/galeri/$', views.galeri, name='galeri'),
    url(r'^profil/informatika/$', views.identitas, name='profil'),
    url(r'^profil/identitas/$', views.identitas, name='identitas'),
    url(r'^profil/staff/$', views.staff, name='staff'),
    url(r'^profil/visi/$', views.visi, name='visi'),
    url(r'^profil/prestasi/$', views.prestasi, name='prestasi'),
    url(r'^kurikulum/$', views.kurikulum, name='kurikulum'),
    url(r'^ukm/fosti/$', views.fosti, name='fosti'),
    url(r'^ukm/himatif/$', views.himatif, name='himatif'),
    url(r'^alumni/$', views.alumni, name='alumni'),
    url(r'^akademik/dokumen/$', views.dokumen, name='dokumen'),



    # url(r'^berita/$', views.listBerita, name='berita'),
    # url(r'^adm/detail_berita/(?P<id>\d+)/$', views.detail_berita, name='detail_berita'),
    # url(r'^timeline/$', views.view_timeline, name='timeline'),




]

dashboard/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from landing.models import alumni_model
from .forms import *
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash,authenticate,login,logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.conf import settings



'''Keperluan Cetak'''
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4, landscape, letter
from reportlab.lib import colors

# Create your views here.

def login_view(request):
    title="Login"
    user = request.user
    if user.is_authenticated():
        return redirect('home:dashboard')
    else:
        form_login = user_login_form(request.POST or  None)
        if form_login.is_valid():
            username = form_login.cleaned_data.get("username")
            password = form_login.cleaned_data.get("password")
            user = authenticate(username=username,password=password)
            login(request,user)
            return  HttpResponseRedirect (settings.LOGIN_REDIRECT_URL)
        context = {
            "form_login" : form_login,
            "title" : title,

        }
        return render(request,"login.html",context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required()
def password_ubah(request):
    title = 'Password'
    if request.method == 'POST':
        form_password = ubah_password(request.user, data=request.POST)
        if form_password.is_valid():
            form_password.save()
            update_session_auth_hash(request, form_password.user)
            messages.success(request, "Password sudah terganti.")
            # return redirect("/")
    else:
        form_password =ubah_password(request.user)
    data = {
        'form_password': form_password,
        'title' : title,
    }
    return render(request, "dashboard/akun/ubah_password.html", data)

@login_required()
def alumni_dashboard(request):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    data_alumni = alumni_model.objects.all()
    context = {
    'data_alumni':data_alumni,
    'title':'Data Alumni',
    }
    return render(request,"dashboard/halaman/alumni.html",context)

@login_required()
def cetak_rekapan_alumni(request):
    if not request.user.is_staff and not request.user.is_superuser:
        raise Http404
    # pengaturan respon berformat pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="rekapan_alumni.pdf"'

    # mengambil daftar kehadiran dan mengubahnya menjadi data ntuk tabel
    data = alumni_model.objects.all()
    table_data = []

    table_data.append([ "NO","Nama","NIM","Konsentrasi","Perusahaan","Posisi","Thn Masuk, Lulus" ])
    i = 1
    for x in data:
        table_data.append([ i,x.nama, x.nim, x.konsentrasi, x.tempat_kerja,x.jabatan,str(x.tahun_masuk)+", "+str(x.tahun_keluar) ])
        i+=1


    # membuat dokumen baru
    doc = SimpleDocTemplate(response, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    styles = getSampleStyleSheet()

    # pengaturan tabel di pdf
    table_style = TableStyle([
                               ('ALIGN',(1,1),(-2,-2),'LEFT'),
                               ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
                               ('VALIGN',(0,0),(0,-1),'TOP'),
                               ('INNERGRID', (0,0), (-1,-1), 0.25, colors.black),
                               ('BOX', (0,0), (-1,-1), 0.25, colors.black),
                           ])
    pendaftar_table = Table(table_data)
    pendaftar_table.setStyle(table_style)

    # mengisi pdf
    content = []
    # logo = "static/img/logo_ums.jpg"
    # im = Image(logo, 2*inch, 2*inch)
    # content.append(im)
    content.append(Paragraph('Daftar Rekapan Mahasiswa Alumni Informatika', styles['Title']))
    content.append(Spacer(1,12))
    # content.append(Paragraph('Berikut ini adalah rekapannya' , styles['Normal']))
    content.append(Spacer(1,12))
    content.append(pendaftar_table)
    content.append(Spacer(1,36))
    # content.append(Paragraph('Mengetahui, ', styles['Normal']))
    # content.append(Spacer(1,48))
    # content.append(Paragraph('Wakil Dekan III ', styles['Normal']))

    # menghasilkan pdf untk di download
    doc.build(content)
    return response

@login_required()
def staff(request):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    data_staff = staff_model.objects.all().filter(posisi='staff')
    context={
    'staff':data_staff,
    'judul':'Staff',
    }
    return render(request,'dashboard/staff/list_staff.html',context)

@login_required()
def dosen_tetap(request):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    data_staff = staff_model.objects.all().filter(posisi='dosen tetap')
    context={
    'staff':data_staff,
    'judul':'Staff',
    }
    return render(request,'dashboard/staff/list_dosen_tetap.html',context)

@login_required()
def dosen_profesi(request):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    data_staff = staff_model.objects.all().filter(posisi='dosen profesi')
    context={
    'staff':data_staff,
    'judul':'Staff',
    }
    return render(request,'dashboard/staff/list_dosen_profesi.html',context)

@login_required()
def staff_tambah(request):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    form_staff = staff_form(request.POST or None, request.FILES or None)
    if form_staff.is_valid():
        data_staff = form_staff.save(commit=False)
        data_staff.posisi = 'staff'
        data_staff.save()
        # messages.success(request,'Data staff sudah tersimpan')
        return redirect('dashboard:staff')
    context={
    'form_staff':form_staff,
    'judul':'Tambah Staff'
    }
    return render(request,'dashboard/staff/tambah_staff.html',context)

@login_required()
def dosen_tetap_tambah(request):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    form_staff = staff_form(request.POST or None, request.FILES or None)
    if form_staff.is_valid():
        data_staff = form_staff.save(commit=False)
        data_staff.posisi = 'dosen tetap'
        data_staff.save()
        # messages.success(request,'Data staff sudah tersimpan')
        return HttpResponseRedirect('../')
    context={
    'form_staff':form_staff,
    'judul':'Tambah Staff'
    }
    return render(request,'dashboard/staff/tambah_dosen_tetap.html',context)

@login_required()
def dosen_profesi_tambah(request):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    form_staff = staff_form(request.POST or None, request.FILES or None)
    if form_staff.is_valid():
        data_staff = form_staff.save(commit=False)
        data_staff.posisi = 'dosen profesi'
        data_staff.save()
        # messages.success(request,'Data staff sudah tersimpan')
        return HttpResponseRedirect('../')
    context={
    'form_staff':form_staff,
    'judul':'Tambah Staff'
    }
    return render(request,'dashboard/staff/tambah_dosen_profesi.html',context)

@login_required()
def staff_edit(request,id=None):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    data_staff = get_object_or_404(staff_model,id=id)
    form_staff = staff_form(request.POST or None, request.FILES or None,instance=data_staff)
    if form_staff.is_valid():
        isi_staff = form_staff.save(commit=False)
        data_staff.save()
        # messages.success(request,'Data staff berhasil diedit..')
        return redirect('dashboard:staff')
    context={
    'form_staff':form_staff,
    'judul':'Edit Staff',
    }
    return render(request,'dashboard/staff/tambah_staff.html',context)

@login_required()
def dosen_tetap_edit(request,id=None):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    data_staff = get_object_or_404(staff_model,id=id)
    form_staff = staff_form(request.POST or None, request.FILES or None,instance=data_staff)
    if form_staff.is_valid():
        isi_staff = form_staff.save(commit=False)
        data_staff.save()
        # messages.success(request,'Data staff berhasil diedit..')
        return HttpResponseRedirect('../../')
    context={
    'form_staff':form_staff,
    'judul':'Edit Staff',
    }
    return render(request,'dashboard/staff/tambah_dosen_tetap.html',context)

@login_required()
def dosen_profesi_edit(request,id=None):
    if not request.user.is_active and not request.user.is_authenticated:
        raise Http404
    data_staff = get_object_or_404(staff_model,id=id)
    form_staff = staff_form(request.POST or None, request.FILES or None,instance=data_staff)
    if form_staff.is_valid():
        isi_staff = form_staff.save(commit=False)
        data_staff.save()
        # messages.success(request,'Data staff berhasil diedit..')
        return HttpResponseRedirect('../..')
    context={
    'form_staff':form_staff,
    'judul':'Edit Staff',
    }
    return render(request,'dashboard/staff/tambah_dosen_profesi.html',context)

@login_required()
def staff_hapus(request,id=None):

templates/dashboard/berita/berita.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}


{% block content %}
<div id="page-wrapper">
<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <ol class="breadcrumb">
                        <li>
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                            <li >
                                <i class=""></i> Berita
                            </li>
                            <li class="active">
                                <i class=""></i> Berita
                            </li>
                        </ol>
                        <h1 class="page-header">
                            Manajemen Berita <small>Semua Berita Staff Prodi Informatika</small>
                        </h1>
                    </div>


                    <div class="col-lg-12">
                     <a href="{% url 'dashboard:tambah_berita' %}" class="btn btn-primary"><i class="fa fa-plus"></i>Tambah Berita</a><br/><br/>
                     {% if beritas %}
            <form class="form-group" method='GET' action=''>
                    <input type='text' name='q' placeholder='Cari Berita' value='{{ request.GET.q }}'/>
                    <input type='submit' class="btn btn-primary" value='Cari' />

                </form>
                     {% for dt in beritas  %}
                <div class="panel panel-default">
                <div class="panel-body">


                        <!-- <img src="{{dt.image.url}}" width="200" height="180"> -->
                        <h3><strong>{{dt.judul}}</strong></h3>
                        <p>{{dt.content|truncatechars:125}}</p>
                         {% if dt.draft %}
                        <p style="color:red"><strong>Draft</strong></p>
                        {% endif %}

                        <a href="{{dt.get_absolute_url}}" class="btn btn-primary">Selengkapnya..</a>

                        </div>
                        <div class="panel-footer">

                        <a href="{% url 'dashboard:edit_berita' slug=dt.slug %}" class="btn btn-primary"><i class="fa fa-edit"></i>Edit </a>
                        <a href="{% url 'dashboard:hapus_berita' slug=dt.slug %}" class="btn btn-danger"><i class="fa fa-trash"></i>Hapus</a>

                        </div>




                </div>

                {% endfor %}
                {% endif %}
                </div>


            </div>
            <!-- /.container-fluid -->
            <hr />
            <center>
            {% if beritas.has_other_pages %}
            <ul class="pagination">
            {% if beritas.has_previous %}
              <li><a href="?page={{ beritas.previous_page_number }}">&laquo;</a></li>
              {% else %}
                  <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in beritas.paginator.page_range %}
                {% if beritas.number == i %}
              <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></a></li>
              {% else %}
              <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
              {% endfor %}
                {% if beritas.has_next %}
              <li><a href="?page={{ beritas.next_page_number }}">&raquo;</a></li>
              {% else %}
              <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}
            </center>


        </div>
        <!-- /#page-wrapper -->

    </div>

    <!-- /#wrapper -->
{% endblock content %}

templates/dashboard/berita/buat_berita.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}
<div id="page-wrapper">
<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <ol class="breadcrumb">
                        <li>
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                            <li >
                                <i class=""></i> Berita
                            </li>
                            <li class="">
                                <i class=""></i> Berita/Pengumuman
                            </li>
                            <li class="active">
                                <i class=""></i> Buat Info
                            </li>
                        </ol>
                        <h1 class="page-header">
                            Manajemen Info <small>Semua Info Prodi Informatika</small>
                        </h1>
                    </div>
                    <div class="col-lg-12">
                    <div class="panel-body">
                        <form method="POST" action="" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form_berita | crispy }}
                            <input type="submit" class="btn btn-primary" value="Simpan">
                            <!--<script>alert("Terima Kasih sudah mendaftar beasiswa, {{ user }}")</script>-->

                        </form>
                    </div>


                    </div>



                </div>


            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

    <!-- /#wrapper -->
{% endblock content %}

templates/dashboard/berita/detail_berita.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}


{% block content %}
<div id="page-wrapper">
<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <ol class="breadcrumb">
                        <li>
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                            <li >
                                <i class=""></i> Berita
                            </li>
                            <li class="active">
                                <i class=""></i> {{obj.judul}}
                            </li>
                        </ol>
                        <h1 class="page-header">
                           {{obj.judul}} <small>Posted {{obj.timestamp|date:"d M Y"}}</small>
                        </h1>
                    </div>


                    <div class="col-md-12">

                    <div class="col-md-5">
                    {% if obj.image %}
                        <img class="img-responsive" src="{{obj.image.url}}">
                        {% endif %}
                        <p>{{obj.content}}</p>
                    </div>

                    </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>

    <!-- /#wrapper -->
{% endblock content %}

templates/dashboard/berita/pengumuman.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}


{% block content %}
<div id="page-wrapper">
<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <ol class="breadcrumb">
                        <li>
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                            <li >
                                <i class=""></i> Berita
                            </li>
                            <li class="active">
                                <i class=""></i> Pengumuman
                            </li>
                        </ol>
                        <h1 class="page-header">
                           Manajemen Pengumuman <small>Semua Pengumuman Staff Prodi Informatika</small>
                        </h1>
                    </div>


                    <div class="col-lg-12">
                     <a href="{% url 'dashboard:tambah_pengumuman' %}" class="btn btn-primary"><i class="fa fa-plus"></i>Tambah Pengumuman</a><br/><br/>
                     {% if pengumuman %}
            <form class="form-group" method='GET' action=''>
                    <input type='text' name='q' placeholder='Cari Berita' value='{{ request.GET.q }}'/>
                    <input type='submit' class="btn btn-primary" value='Cari' />

                </form>
                     {% for dt in pengumuman %}
                <div class="panel panel-default">
                <div class="panel-body">
                        <h3><strong>{{dt.judul}}</strong></h3><br/>
                        <p>{{dt.content|truncatechars:125}}</p>
                        {% if dt.draft %}
                        <p style="color:red"><strong>Draft</strong></p>
                        {% endif %}
                        <a href="{{dt.get_absolute_url}}" class="btn btn-primary">Selengkapnya..</a></div>

                        <div class="panel-footer">
                        <a href="{% url 'dashboard:edit_pengumuman' slug=dt.slug %}" class="btn btn-primary"><i class="fa fa-edit"></i>Edit</a>
                        <a href="{% url 'dashboard:hapus_pengumuman' slug=dt.slug %}" class="btn btn-danger"><i class="fa fa-trash"></i>Hapus</a>
                        </div>


                        </div>

                        {% endfor %}
                        {% endif %}


                </div>

            </div>
            <!-- /.container-fluid -->
            <hr />
            <center>
            {% if pengumuman.has_other_pages %}
            <ul class="pagination">
            {% if pengumuman.has_previous %}
              <li><a href="?page={{ pengumuman.previous_page_number }}">&laquo;</a></li>
              {% else %}
                  <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in pengumuman.paginator.page_range %}
                {% if pengumuman.number == i %}
              <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></a></li>
              {% else %}
              <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
              {% endfor %}
                {% if pengumuman.has_next %}
              <li><a href="?page={{ pengumuman.next_page_number }}">&raquo;</a></li>
              {% else %}
              <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}
            </center>
        </div>
        <!-- /#page-wrapper -->

    </div>

    <!-- /#wrapper -->
{% endblock content %}